SERVICES = {
  'gcorreiaS' => {
    ip: '192.168.56.110',
    ram: '2048',
    cpus: '2'
  }
}

Vagrant.configure("2") do |config|
  # Common configuration
  config.vm.box = "bento/debian-13.1"
  config.vm.synced_folder "vars/", "/srv/vars", create: true
  
  # gcorreia Server 
  config.vm.define "gcorreiaS" do |gs|

    # VM specs configuration 
    config.vm.provider "virtualbox" do |vb|
      vb.memory = SERVICES['gcorreiaS'][:ram]
      vb.cpus = SERVICES['gcorreiaS'][:cpus]
    end

    # Network configuration
    gs.vm.hostname = "gcorreiaS"
    gs.vm.network "private_network", ip: SERVICES['gcorreiaS'][:ip]

    # Shell setup
    gs.vm.provision "shell", name: "install-k3s-Server", inline: <<-SHELL
      echo "### Installing K3s server ###"
      export INSTALL_K3S_EXEC="--write-kubeconfig-mode=644 --node-ip=#{SERVICES['gcorreiaS'][:ip]}"
      curl -sfL https://get.k3s.io | sh -

      echo "### Bringing up pods ###"
      kubectl apply -f /srv/vars/manifest.yaml
    SHELL
  end
end
