# Service configuration reference
SERVICES = {
  'gcorreiaS' => {
    ip: '192.168.56.110'
  }
}

Vagrant.configure("2") do |config|
  # Common configuration
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "2"
  end
  
  # Common provisioning script for all VMs
  # config.vm.provision "shell", name: "install-systemd", inline: <<-SHELL
  #   apt install systemd -y
  # SHELL

  # gcorreia Server 
  config.vm.define "gcorreiaS" do |gs|
    gs.vm.hostname = "gcorreiaS"
    gs.vm.network "private_network", ip: SERVICES['gcorreiaS'][:ip]

    gs.vm.provision "shell", name: "install-k3s", inline: <<-SHELL
      curl -sfL https://get.k3s.io | sh -
    SHELL
  end
end
